/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.TelaEscolha;


import br.edu.calcIAC.calcIAC;
import br.edu.login.view.calcIMC;

/**
 *
 * Tela de escolha do usuário de calculadora IMC ou calculadora IAC.
 */
public class TelaEscolha extends javax.swing.JFrame {

    /**
     * Creates new form TelaEscolha
     */
    public TelaEscolha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnIAC = new javax.swing.JButton();
        btnIMC = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/login/images/EscolhaFundo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnIAC.setContentAreaFilled(false);
        btnIAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIACMouseClicked(evt);
            }
        });
        btnIAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIACActionPerformed(evt);
            }
        });
        getContentPane().add(btnIAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 80, 90));

        btnIMC.setContentAreaFilled(false);
        btnIMC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIMCMouseClicked(evt);
            }
        });
        btnIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIMCActionPerformed(evt);
            }
        });
        getContentPane().add(btnIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 80, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIACActionPerformed

    private void btnIACMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIACMouseClicked
        calcIAC calc = new calcIAC();
        this.dispose();
        calc.setVisible(true);
    }//GEN-LAST:event_btnIACMouseClicked

    private void btnIMCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIMCMouseClicked
        calcIMC calc = new calcIMC();
        this.dispose();
        calc.setVisible(true);
    }//GEN-LAST:event_btnIMCMouseClicked

    private void btnIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEscolha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIAC;
    private javax.swing.JButton btnIMC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
