/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.calcIAC;

import br.edu.TelaEscolha.TelaEscolha;
import java.text.DecimalFormat;

/**
 *
 * Tela de calculadora IAC (Indice de adiposidade corporal).
 */
public class calcIAC extends javax.swing.JFrame {

    /**
     * Creates new form calcIAC
     */
    public calcIAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quadril = new javax.swing.JTextField();
        Altura = new javax.swing.JTextField();
        Resultado = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        FundoIAC = new javax.swing.JLabel();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quadril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuadrilActionPerformed(evt);
            }
        });
        getContentPane().add(Quadril, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 170, -1));

        Altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlturaActionPerformed(evt);
            }
        });
        getContentPane().add(Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 170, -1));

        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 170, -1));

        btnCalcular.setText("Calcular");
        btnCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalcularMouseClicked(evt);
            }
        });
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        FundoIAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/login/images/CalculadoraIAC.jpg"))); // NOI18N
        getContentPane().add(FundoIAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnRetornar.setContentAreaFilled(false);
        btnRetornar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetornarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 10, 80, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void QuadrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuadrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuadrilActionPerformed

    private void AlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlturaActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalcularMouseClicked
        double result = Double.parseDouble(Quadril.getText()) / ( Double.parseDouble(Altura.getText())* Math.sqrt(Double.parseDouble(Altura.getText())) );
        result = result - 18;
        String valorFormatado = new DecimalFormat("#,##0.00").format(result);
        
        Resultado.setText(String.valueOf(valorFormatado));
    }//GEN-LAST:event_btnCalcularMouseClicked

    private void btnRetornarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetornarMouseClicked
      TelaEscolha calc = new TelaEscolha();
       this.dispose();
       calc.setVisible(true);
    }//GEN-LAST:event_btnRetornarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcIAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcIAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Altura;
    private javax.swing.JLabel FundoIAC;
    private javax.swing.JTextField Quadril;
    private javax.swing.JTextField Resultado;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnRetornar;
    // End of variables declaration//GEN-END:variables
}
